version: "3"

services:
  api: &app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CELERY_BROKER_URL: redis://redis/0
      CELERY_RESULT_BACKEND: redis://redis/1
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/app
    entrypoint: sh
    command:
      - "-c"
      - "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
    depends_on: ["redis"]

  worker:
    <<: *app
    command:
      - "-c"
      - "celery -A app.celery worker -l info"
    restart: unless-stopped
    ports: []

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
